# Generated by Django 4.2 on 2023-05-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoWatch', '0003_alter_video_profile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
